// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.18052
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Automation_Framework.Tests.Mercury
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Book Tickets")]
    public partial class BookTicketsFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "BookTickets.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Book Tickets", "DESCRIPTION: As a User i should be able to complete the Ticket Booking Process an" +
                    "d be able to book a ticket successfully", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Book Tickets - Use NAME Locators")]
        [NUnit.Framework.CategoryAttribute("Priority:Medium")]
        public virtual void BookTickets_UseNAMELocators()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Book Tickets - Use NAME Locators", new string[] {
                        "Priority:Medium"});
#line 5
this.ScenarioSetup(scenarioInfo);
#line 6
testRunner.Given("I am on the site \'http://newtours.demoaut.com/\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 7
testRunner.When("I enter text \'mrsethgaurav\' in the TextBox \'userName\' searched by \'NAME\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 8
testRunner.When("I enter text \'letmein\' in the TextBox \'password\' searched by \'NAME\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 9
testRunner.When("I click on the Button \'input[type=\'image\'][alt=\'Sign-In\']\' searched by \'CSS\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 10
testRunner.Then("I should see the site title as \'Find a Flight: Mercury Tours:\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 11
testRunner.When("I select drop down value \'London\' from the DropDown Box \'fromPort\' searched by \'X" +
                    "PATH\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 12
testRunner.When("I select drop down value \'New York\' from the DropDown Box \'toPort\' searched by \'X" +
                    "PATH\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 13
testRunner.When("user selects Radio Button Value \'Business class\' from RadioButtonGroup \'Business\'" +
                    " searched by \'NAME\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 14
testRunner.When("I click on the Button \'findFlights\' searched by \'NAME\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 15
testRunner.Then("i close the Site", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Book Tickets - Use CSS Locators")]
        [NUnit.Framework.CategoryAttribute("Priority:Medium")]
        public virtual void BookTickets_UseCSSLocators()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Book Tickets - Use CSS Locators", new string[] {
                        "Priority:Medium"});
#line 19
this.ScenarioSetup(scenarioInfo);
#line 20
testRunner.Given("I am on the site \'http://newtours.demoaut.com/\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 21
testRunner.Then("I should see the site title as \'Welcome: Mercury Tours\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 22
testRunner.When("I enter text \'mrsethgaurav\' in the TextBox \'input[name=\'userName\'][type=\'text\']\' " +
                    "searched by \'CSS\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 23
testRunner.When("I enter text \'letmein\' in the TextBox \'input[name=\'password\'][type=\'password\']\' s" +
                    "earched by \'CSS\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 24
testRunner.When("I click on the Button \'input[type=\'image\'][alt=\'Sign-In\']\' searched by \'CSS\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 25
testRunner.Then("I should see the site title as \'Find a Flight: Mercury Tours:\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 26
testRunner.When("I select drop down value \'London\' from the DropDown Box \'select[name=\'fromPort\']\'" +
                    " searched by \'CSS\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 27
testRunner.When("I select drop down value \'New York\' from the DropDown Box \'select[name=\'toPort\']\'" +
                    " searched by \'CSS\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 28
testRunner.When("user selects Radio Button Value \'Business class\' from RadioButtonGroup \'input[typ" +
                    "e=\'radio\'][value=\'Business\']\' searched by \'CSS\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 29
testRunner.When("I click on the Button \'input[type=\'image\'][name=\'findFlights\'][src=\'/images/forms" +
                    "/continue.gif\']\' searched by \'CSS\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 30
testRunner.When("I click on the Button \'input[type=\'image\'][name=\'reserveFlights\'][src=\'/images/fo" +
                    "rms/continue.gif\']\' searched by \'CSS\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 32
testRunner.When("I enter text \'Arti\' in the TextBox \'input[name=\'passFirst0\']\' searched by \'CSS\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 33
testRunner.When("I enter text \'Seth\' in the TextBox \'input[name=\'passLast0\']\' searched by \'CSS\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 34
testRunner.When("I select drop down value \'Vegetarian\' from the DropDown Box \'select[name=\'pass.0." +
                    "meal\']\' searched by \'CSS\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 35
testRunner.When("I select drop down value \'MasterCard\' from the DropDown Box \'select[name=\'creditC" +
                    "ard\']\' searched by \'CSS\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 36
testRunner.When("I enter text \'123456789\' in the TextBox \'input[name=\'creditnumber\'][type=\'text\']\'" +
                    " searched by \'CSS\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 37
testRunner.When("I select drop down value \'12\' from the DropDown Box \'select[name=\'cc_exp_dt_mn\']\'" +
                    " searched by \'CSS\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 38
testRunner.When("I select drop down value \'2010\' from the DropDown Box \'select[name=\'cc_exp_dt_yr\'" +
                    "]\' searched by \'CSS\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 39
testRunner.When("I enter text \'Gaurav\' in the TextBox \'input[name=\'cc_frst_name\'][type=\'text\']\' se" +
                    "arched by \'CSS\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 40
testRunner.When("I enter text \'Seth\' in the TextBox \'input[name=\'cc_last_name\'][type=\'text\']\' sear" +
                    "ched by \'CSS\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 42
testRunner.When("I turn the CheckBox \'input[type=\'checkbox\'][name=\'ticketLess\']\' searched by \'CSS\'" +
                    " to \'ON\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 43
testRunner.When("I enter text \'16, Dashmesh Avenue, PORS Mills\' in the TextBox \'input[name=\'billAd" +
                    "dress1\']\' searched by \'CSS\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 44
testRunner.When("I enter text \'Amritsar\' in the TextBox \'input[name=\'billCity\']\' searched by \'CSS\'" +
                    "", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 45
testRunner.When("I enter text \'Punjab\' in the TextBox \'input[name=\'billState\']\' searched by \'CSS\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 46
testRunner.When("I select drop down value \'INDIA\' from the DropDown Box \'select[name=\'billCountry\'" +
                    "]\' searched by \'CSS\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 48
testRunner.When("I enter text \'Basement Flat, 173 Belle Vue Road\' in the TextBox \'input[name=\'delA" +
                    "ddress1\']\' searched by \'CSS\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 49
testRunner.When("I enter text \'Leeds\' in the TextBox \'input[name=\'delCity\']\' searched by \'CSS\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 50
testRunner.When("I enter text \'West Yorkshire\' in the TextBox \'input[name=\'delState\']\' searched by" +
                    " \'CSS\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 51
testRunner.When("I enter text \'LS3 1DU\' in the TextBox \'input[name=\'delZip\']\' searched by \'CSS\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 53
testRunner.When("I click on the Button \'input[type=\'image\'][name=\'buyFlights\'][src=\'/images/forms/" +
                    "purchase.gif\']\' searched by \'CSS\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 54
testRunner.Then("i close the Site", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Book Tickets - Use XPATH")]
        [NUnit.Framework.CategoryAttribute("Priority:Medium")]
        public virtual void BookTickets_UseXPATH()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Book Tickets - Use XPATH", new string[] {
                        "Priority:Medium"});
#line 58
this.ScenarioSetup(scenarioInfo);
#line 59
testRunner.Given("I am on the site \'http://newtours.demoaut.com/\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 60
testRunner.Then("I should see the site title as \'Welcome: Mercury Tours\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 61
testRunner.When("I enter text \'mrsethgaurav\' in the TextBox \'//input[@name=\'userName\']\' searched b" +
                    "y \'XPATH\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 62
testRunner.When("I enter text \'letmein\' in the TextBox \'//input[@name=\'password\'][@type=\'password\'" +
                    "]\' searched by \'XPATH\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 63
testRunner.When("I click on the Button \'//input[@type=\'image\'][@alt=\'Sign-In\']\' searched by \'XPATH" +
                    "\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 64
testRunner.Then("I should see the site title as \'Find a Flight: Mercury Tours:\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 65
testRunner.When("I select drop down value \'London\' from the DropDown Box \'//select[@name=\'fromPort" +
                    "\']\' searched by \'XPATH\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 66
testRunner.When("I select drop down value \'New York\' from the DropDown Box \'//select[@name=\'toPort" +
                    "\']\' searched by \'XPATH\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 67
testRunner.When("user selects Radio Button Value \'Business class\' from RadioButtonGroup \'//input[@" +
                    "type=\'radio\'][@value=\'Business\']\' searched by \'XPATH\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 68
testRunner.When("I click on the Button \'//input[type=\'image\'][@name=\'findFlights\']\' searched by \'X" +
                    "PATH\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 69
testRunner.When("I click on the Button \'//input[type=\'image\'][@name=\'reserveFlights\']\' searched by" +
                    " \'XPATH\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 71
testRunner.When("I enter text \'Arti\' in the TextBox \'//input[@name=\'passFirst0\']\' searched by \'XPA" +
                    "TH\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 72
testRunner.When("I enter text \'Seth\' in the TextBox \'//input[@name=\'passLast0\']\' searched by \'XPAT" +
                    "H\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 73
testRunner.When("I select drop down value \'Vegetarian\' from the DropDown Box \'//select[@name=\'pass" +
                    ".0.meal\']\' searched by \'XPATH\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 74
testRunner.When("I select drop down value \'MasterCard\' from the DropDown Box \'//select[@name=\'cred" +
                    "itCard\']\' searched by \'XPATH\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 75
testRunner.When("I enter text \'123456789\' in the TextBox \'//input[@name=\'creditnumber\'][@type=\'tex" +
                    "t\']\' searched by \'XPATH\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 76
testRunner.When("I select drop down value \'12\' from the DropDown Box \'//select[@name=\'cc_exp_dt_mn" +
                    "\']\' searched by \'XPATH\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 77
testRunner.When("I select drop down value \'2010\' from the DropDown Box \'//select[@name=\'cc_exp_dt_" +
                    "yr\']\' searched by \'XPATH\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 78
testRunner.When("I enter text \'Gaurav\' in the TextBox \'//input[@name=\'cc_frst_name\'][@type=\'text\']" +
                    "\' searched by \'XPATH\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 79
testRunner.When("I enter text \'Seth\' in the TextBox \'//input[@name=\'cc_last_name\'][@type=\'text\']\' " +
                    "searched by \'XPATH\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 81
testRunner.When("I turn the CheckBox \'//input[@type=\'checkbox\'][@name=\'ticketLess\']\' searched by \'" +
                    "XPATH\' to \'ON\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 82
testRunner.When("I enter text \'16, Dashmesh Avenue, PORS Mills\' in the TextBox \'//input[@name=\'bil" +
                    "lAddress1\']\' searched by \'XPATH\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 83
testRunner.When("I enter text \'Amritsar\' in the TextBox \'//input[@name=\'billCity\']\' searched by \'X" +
                    "PATH\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 84
testRunner.When("I enter text \'Punjab\' in the TextBox \'//input[@name=\'billState\']\' searched by \'XP" +
                    "ATH\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 85
testRunner.When("I select drop down value \'INDIA\' from the DropDown Box \'//select[@name=\'billCount" +
                    "ry\']\' searched by \'XPATH\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 87
testRunner.When("I enter text \'Basement Flat, 173 Belle Vue Road\' in the TextBox \'//input[@name=\'d" +
                    "elAddress1\']\' searched by \'XPATH\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 88
testRunner.When("I enter text \'Leeds\' in the TextBox \'//input[@name=\'delCity\']\' searched by \'XPATH" +
                    "\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 89
testRunner.When("I enter text \'West Yorkshire\' in the TextBox \'//input[@name=\'delState\']\' searched" +
                    " by \'XPATH\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 90
testRunner.When("I enter text \'LS3 1DU\' in the TextBox \'//input[@name=\'delZip\']\' searched by \'XPAT" +
                    "H\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 92
testRunner.When("I click on the Button \'//input[@type=\'image\'][@name=\'buyFlights\'][@src=\'/images/f" +
                    "orms/purchase.gif\']\' searched by \'XPATH\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 93
testRunner.Then("i close the Site", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
